// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NemetschekDnevnik.Server.Models;

#nullable disable

namespace NemetschekDnevnik.Server.Migrations
{
    [DbContext(typeof(NemetschekSchoolDiaryContext))]
    [Migration("20260707114226_test2")]
    partial class test2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("admin_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("last_name");

                    b.HasKey("AdminId")
                        .HasName("PK__admin__43AA4141760C7B9D");

                    b.ToTable("admin", (string)null);
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Attendance", b =>
                {
                    b.Property<int>("LessonId")
                        .HasColumnType("int")
                        .HasColumnName("lesson_id");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.HasKey("LessonId", "StudentId")
                        .HasName("PK__attendan__D682C7D756588763");

                    b.HasIndex("StudentId");

                    b.ToTable("attendance", (string)null);
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<int>("ClassGrade")
                        .HasColumnType("int")
                        .HasColumnName("class_grade");

                    b.Property<string>("ClassLetter")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("class_letter");

                    b.Property<int?>("HeadTeacherId")
                        .HasColumnType("int")
                        .HasColumnName("head_teacher_id");

                    b.HasKey("ClassId")
                        .HasName("PK__classes__FDF479865BC9999C");

                    b.HasIndex("HeadTeacherId");

                    b.ToTable("classes", (string)null);
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("grade_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<string>("GradeValue")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("grade_value");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.HasKey("GradeId")
                        .HasName("PK__grades__3A8F732CB19F1828");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("grades", (string)null);
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.HomeworkItem", b =>
                {
                    b.Property<int>("HomeworkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("homework_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HomeworkId"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<DateOnly>("DateDue")
                        .HasColumnType("date")
                        .HasColumnName("date_due");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectLink")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("subject_link");

                    b.HasKey("HomeworkId")
                        .HasName("PK__homework__FD60442A6A30E660");

                    b.HasIndex("ClassId");

                    b.HasIndex("SubjectId");

                    b.ToTable("homework_items", (string)null);
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Parent", b =>
                {
                    b.Property<int>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("phone_number");

                    b.HasKey("ParentId")
                        .HasName("PK__parent__F2A6081978DDDBAC");

                    b.ToTable("parent", (string)null);
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("phone_number");

                    b.HasKey("StudentId")
                        .HasName("PK__student__2A33069A4369D820");

                    b.ToTable("student", (string)null);
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("subject_name");

                    b.HasKey("SubjectId")
                        .HasName("PK__subjects__5004F660E965A954");

                    b.ToTable("subjects", (string)null);
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("phone_number");

                    b.HasKey("TeacherId")
                        .HasName("PK__teacher__03AE777EA9BB80AB");

                    b.ToTable("teacher", (string)null);
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit")
                        .HasColumnName("is_approved");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role");

                    b.HasKey("UserId")
                        .HasName("PK__users__B9BE370FB3BC4991");

                    b.HasIndex(new[] { "Email" }, "UQ__users__AB6E6164CC0E5DCB")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.WeeklySchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("schedule_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("location");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time")
                        .HasColumnName("time");

                    b.HasKey("ScheduleId")
                        .HasName("PK__weekly_s__C46A8A6FD887C6DA");

                    b.HasIndex("ClassId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("weekly_schedules", (string)null);
                });

            modelBuilder.Entity("ParentStudent", b =>
                {
                    b.Property<int>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("ParentId", "StudentId")
                        .HasName("PK__parent_s__40053870C72F1416");

                    b.HasIndex("StudentId");

                    b.ToTable("parent_student", (string)null);
                });

            modelBuilder.Entity("StudentClass", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.HasKey("StudentId", "ClassId")
                        .HasName("PK__student___55EC4102B001E1B4");

                    b.HasIndex("ClassId");

                    b.ToTable("student_class", (string)null);
                });

            modelBuilder.Entity("TeacherSubject", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    b.HasKey("TeacherId", "SubjectId")
                        .HasName("PK__teacher___16AE381830780335");

                    b.HasIndex("SubjectId");

                    b.ToTable("teacher_subjects", (string)null);
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Admin", b =>
                {
                    b.HasOne("NemetschekDnevnik.Server.Models.User", "AdminNavigation")
                        .WithOne("Admin")
                        .HasForeignKey("NemetschekDnevnik.Server.Models.Admin", "AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__admin__admin_id__59063A47");

                    b.Navigation("AdminNavigation");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Attendance", b =>
                {
                    b.HasOne("NemetschekDnevnik.Server.Models.WeeklySchedule", "Lesson")
                        .WithMany("Attendances")
                        .HasForeignKey("LessonId")
                        .IsRequired()
                        .HasConstraintName("FK__attendanc__lesso__68487DD7");

                    b.HasOne("NemetschekDnevnik.Server.Models.Student", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__attendanc__stude__693CA210");

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Class", b =>
                {
                    b.HasOne("NemetschekDnevnik.Server.Models.Teacher", "HeadTeacher")
                        .WithMany("Classes")
                        .HasForeignKey("HeadTeacherId")
                        .HasConstraintName("FK__classes__head_te__5CD6CB2B");

                    b.Navigation("HeadTeacher");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Grade", b =>
                {
                    b.HasOne("NemetschekDnevnik.Server.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__grades__student___6E01572D");

                    b.HasOne("NemetschekDnevnik.Server.Models.Subject", "Subject")
                        .WithMany("Grades")
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("FK__grades__subject___6D0D32F4");

                    b.HasOne("NemetschekDnevnik.Server.Models.Teacher", "Teacher")
                        .WithMany("Grades")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("FK__grades__teacher___6EF57B66");

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.HomeworkItem", b =>
                {
                    b.HasOne("NemetschekDnevnik.Server.Models.Class", "Class")
                        .WithMany("HomeworkItems")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK__homework___class__71D1E811");

                    b.HasOne("NemetschekDnevnik.Server.Models.Subject", "Subject")
                        .WithMany("HomeworkItems")
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("FK__homework___subje__72C60C4A");

                    b.Navigation("Class");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Parent", b =>
                {
                    b.HasOne("NemetschekDnevnik.Server.Models.User", "ParentNavigation")
                        .WithOne("Parent")
                        .HasForeignKey("NemetschekDnevnik.Server.Models.Parent", "ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__parent__parent_i__4BAC3F29");

                    b.Navigation("ParentNavigation");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Student", b =>
                {
                    b.HasOne("NemetschekDnevnik.Server.Models.User", "StudentNavigation")
                        .WithOne("Student")
                        .HasForeignKey("NemetschekDnevnik.Server.Models.Student", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__student__student__48CFD27E");

                    b.Navigation("StudentNavigation");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Teacher", b =>
                {
                    b.HasOne("NemetschekDnevnik.Server.Models.User", "TeacherNavigation")
                        .WithOne("Teacher")
                        .HasForeignKey("NemetschekDnevnik.Server.Models.Teacher", "TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__teacher__teacher__52593CB8");

                    b.Navigation("TeacherNavigation");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.WeeklySchedule", b =>
                {
                    b.HasOne("NemetschekDnevnik.Server.Models.Class", "Class")
                        .WithMany("WeeklySchedules")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK__weekly_sc__class__6477ECF3");

                    b.HasOne("NemetschekDnevnik.Server.Models.Subject", "Subject")
                        .WithMany("WeeklySchedules")
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("FK__weekly_sc__subje__6383C8BA");

                    b.HasOne("NemetschekDnevnik.Server.Models.Teacher", "Teacher")
                        .WithMany("WeeklySchedules")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("FK__weekly_sc__teach__656C112C");

                    b.Navigation("Class");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("ParentStudent", b =>
                {
                    b.HasOne("NemetschekDnevnik.Server.Models.Parent", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .IsRequired()
                        .HasConstraintName("FK__parent_st__paren__4E88ABD4");

                    b.HasOne("NemetschekDnevnik.Server.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__parent_st__stude__4F7CD00D");
                });

            modelBuilder.Entity("StudentClass", b =>
                {
                    b.HasOne("NemetschekDnevnik.Server.Models.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK__student_c__class__60A75C0F");

                    b.HasOne("NemetschekDnevnik.Server.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__student_c__stude__5FB337D6");
                });

            modelBuilder.Entity("TeacherSubject", b =>
                {
                    b.HasOne("NemetschekDnevnik.Server.Models.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK__teacher_s__subje__5629CD9C");

                    b.HasOne("NemetschekDnevnik.Server.Models.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("FK__teacher_s__teach__5535A963");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Class", b =>
                {
                    b.Navigation("HomeworkItems");

                    b.Navigation("WeeklySchedules");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Student", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Grades");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Subject", b =>
                {
                    b.Navigation("Grades");

                    b.Navigation("HomeworkItems");

                    b.Navigation("WeeklySchedules");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Teacher", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Grades");

                    b.Navigation("WeeklySchedules");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.User", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Parent");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.WeeklySchedule", b =>
                {
                    b.Navigation("Attendances");
                });
#pragma warning restore 612, 618
        }
    }
}
