// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NemetschekDnevnik.Server.Models;

#nullable disable

namespace NemetschekDnevnik.Server.Migrations
{
    [DbContext(typeof(NemetschekSchoolDiaryContext))]
    partial class NemetschekSchoolDiaryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("admin_id");

                    b.HasKey("AdminId")
                        .HasName("PK__admin__43AA41416A23D12D");

                    b.ToTable("admin", (string)null);
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Attendance", b =>
                {
                    b.Property<int>("LessonId")
                        .HasColumnType("int")
                        .HasColumnName("lesson_id");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<bool>("IsAbsent")
                        .HasColumnType("bit")
                        .HasColumnName("is_absent");

                    b.Property<bool>("IsExcused")
                        .HasColumnType("bit")
                        .HasColumnName("is_excused");

                    b.HasKey("LessonId", "StudentId")
                        .HasName("PK__attendan__D682C7D7E114F3DE");

                    b.HasIndex("StudentId");

                    b.ToTable("attendance", (string)null);
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<int>("ClassGrade")
                        .HasColumnType("int")
                        .HasColumnName("class_grade");

                    b.Property<string>("ClassLetter")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("class_letter");

                    b.Property<int?>("HeadTeacherId")
                        .HasColumnType("int")
                        .HasColumnName("head_teacher_id");

                    b.HasKey("ClassId")
                        .HasName("PK__classes__FDF4798618B5F560");

                    b.HasIndex("HeadTeacherId");

                    b.ToTable("classes", (string)null);
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("grade_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("comment");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<int?>("GradeTypeId")
                        .HasColumnType("int")
                        .HasColumnName("grade_type_id");

                    b.Property<decimal>("GradeValue")
                        .HasColumnType("decimal(3, 2)")
                        .HasColumnName("grade_value");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.HasKey("GradeId")
                        .HasName("PK__grades__3A8F732CFED7D652");

                    b.HasIndex("GradeTypeId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("grades", (string)null);
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.GradeType", b =>
                {
                    b.Property<int>("GradeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("grade_type_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeTypeId"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type_name");

                    b.HasKey("GradeTypeId")
                        .HasName("PK__grade_ty__31F4E60D09520132");

                    b.ToTable("grade_types", (string)null);
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.HomeworkItem", b =>
                {
                    b.Property<int>("HomeworkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("homework_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HomeworkId"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("DateAssigned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("date_assigned")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("DateDue")
                        .HasColumnType("datetime")
                        .HasColumnName("date_due");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("ResourceLink")
                        .HasMaxLength(550)
                        .IsUnicode(false)
                        .HasColumnType("varchar(550)")
                        .HasColumnName("resource_link");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasDefaultValue("Домашно задание")
                        .HasColumnName("title");

                    b.HasKey("HomeworkId")
                        .HasName("PK__homework__FD60442ADE5A56DA");

                    b.HasIndex("ClassId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("homework_items", (string)null);
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Lesson", b =>
                {
                    b.Property<int>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("lesson_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LessonId"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int?>("ScheduleItemId")
                        .HasColumnType("int")
                        .HasColumnName("schedule_item_id");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time")
                        .HasColumnName("time");

                    b.HasKey("LessonId")
                        .HasName("PK__lessons__6421F7BEFFB3A617");

                    b.HasIndex("ClassId");

                    b.HasIndex("ScheduleItemId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("lessons", (string)null);
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Parent", b =>
                {
                    b.Property<int>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.HasKey("ParentId")
                        .HasName("PK__parent__F2A60819165AFAB8");

                    b.ToTable("parent", (string)null);
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.RefreshToken", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Remark", b =>
                {
                    b.Property<int>("RemarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("remark_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RemarkId"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.HasKey("RemarkId")
                        .HasName("PK__remarks__D46DA2D906BAA593");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("remarks", (string)null);
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.HasKey("StudentId")
                        .HasName("PK__student__2A33069A22388D38");

                    b.HasIndex("ParentId");

                    b.ToTable("student", (string)null);
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("subject_name");

                    b.HasKey("SubjectId")
                        .HasName("PK__subjects__5004F6600397BCF4");

                    b.ToTable("subjects", (string)null);
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.SubmittedHomework", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("submission_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionId"));

                    b.Property<string>("FileLink")
                        .HasMaxLength(550)
                        .IsUnicode(false)
                        .HasColumnType("varchar(550)")
                        .HasColumnName("file_link");

                    b.Property<int?>("HomeworkId")
                        .HasColumnType("int")
                        .HasColumnName("homework_id");

                    b.Property<bool>("IsGraded")
                        .HasColumnType("bit")
                        .HasColumnName("is_graded");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<string>("SubmissionText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("submission_text");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("submitted_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TeacherFeedback")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("teacher_feedback");

                    b.HasKey("SubmissionId")
                        .HasName("PK__submitte__9B5355957BC8AEF5");

                    b.HasIndex("HomeworkId");

                    b.HasIndex("StudentId");

                    b.ToTable("submitted_homeworks", (string)null);
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.HasKey("TeacherId")
                        .HasName("PK__teacher__03AE777ECC09F8E1");

                    b.ToTable("teacher", (string)null);
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit")
                        .HasColumnName("is_approved");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role");

                    b.HasKey("UserId")
                        .HasName("PK__users__B9BE370F8F2732C5");

                    b.HasIndex(new[] { "Email" }, "UQ__users__AB6E61649DF4B344")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.WeeklyScheduleItem", b =>
                {
                    b.Property<int>("ScheduleItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("schedule_item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleItemId"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int")
                        .HasColumnName("day_of_week");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("location");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time")
                        .HasColumnName("time");

                    b.HasKey("ScheduleItemId")
                        .HasName("PK__weekly_s__23BB45AD8B634EEF");

                    b.HasIndex("ClassId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("weekly_schedule_items", (string)null);
                });

            modelBuilder.Entity("StudentClass", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.HasKey("StudentId", "ClassId")
                        .HasName("PK__student___55EC4102AB35D74E");

                    b.HasIndex("ClassId");

                    b.ToTable("student_class", (string)null);
                });

            modelBuilder.Entity("TeacherSubject", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    b.HasKey("TeacherId", "SubjectId")
                        .HasName("PK__teacher___16AE3818951F373C");

                    b.HasIndex("SubjectId");

                    b.ToTable("teacher_subjects", (string)null);
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Admin", b =>
                {
                    b.HasOne("NemetschekDnevnik.Server.Models.User", "AdminNavigation")
                        .WithOne("Admin")
                        .HasForeignKey("NemetschekDnevnik.Server.Models.Admin", "AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__admin__admin_id__4AB81AF0");

                    b.Navigation("AdminNavigation");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Attendance", b =>
                {
                    b.HasOne("NemetschekDnevnik.Server.Models.Lesson", "Lesson")
                        .WithMany("Attendances")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__attendanc__lesso__6477ECF3");

                    b.HasOne("NemetschekDnevnik.Server.Models.Student", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__attendanc__stude__656C112C");

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Class", b =>
                {
                    b.HasOne("NemetschekDnevnik.Server.Models.Teacher", "HeadTeacher")
                        .WithMany("Classes")
                        .HasForeignKey("HeadTeacherId")
                        .HasConstraintName("FK__classes__head_te__52593CB8");

                    b.Navigation("HeadTeacher");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Grade", b =>
                {
                    b.HasOne("NemetschekDnevnik.Server.Models.GradeType", "GradeType")
                        .WithMany("Grades")
                        .HasForeignKey("GradeTypeId")
                        .HasConstraintName("FK__grades__grade_ty__6E01572D");

                    b.HasOne("NemetschekDnevnik.Server.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__grades__student___6C190EBB");

                    b.HasOne("NemetschekDnevnik.Server.Models.Subject", "Subject")
                        .WithMany("Grades")
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("FK__grades__subject___6B24EA82");

                    b.HasOne("NemetschekDnevnik.Server.Models.Teacher", "Teacher")
                        .WithMany("Grades")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("FK__grades__teacher___6D0D32F4");

                    b.Navigation("GradeType");

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.HomeworkItem", b =>
                {
                    b.HasOne("NemetschekDnevnik.Server.Models.Class", "Class")
                        .WithMany("HomeworkItems")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK__homework___class__76969D2E");

                    b.HasOne("NemetschekDnevnik.Server.Models.Subject", "Subject")
                        .WithMany("HomeworkItems")
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("FK__homework___subje__778AC167");

                    b.HasOne("NemetschekDnevnik.Server.Models.Teacher", "Teacher")
                        .WithMany("HomeworkItems")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("FK__homework___teach__787EE5A0");

                    b.Navigation("Class");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Lesson", b =>
                {
                    b.HasOne("NemetschekDnevnik.Server.Models.Class", "Class")
                        .WithMany("Lessons")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK__lessons__class_i__60A75C0F");

                    b.HasOne("NemetschekDnevnik.Server.Models.WeeklyScheduleItem", "ScheduleItem")
                        .WithMany("Lessons")
                        .HasForeignKey("ScheduleItemId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__lessons__schedul__619B8048");

                    b.HasOne("NemetschekDnevnik.Server.Models.Subject", "Subject")
                        .WithMany("Lessons")
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("FK__lessons__subject__5EBF139D");

                    b.HasOne("NemetschekDnevnik.Server.Models.Teacher", "Teacher")
                        .WithMany("Lessons")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("FK__lessons__teacher__5FB337D6");

                    b.Navigation("Class");

                    b.Navigation("ScheduleItem");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Parent", b =>
                {
                    b.HasOne("NemetschekDnevnik.Server.Models.User", "ParentNavigation")
                        .WithOne("Parent")
                        .HasForeignKey("NemetschekDnevnik.Server.Models.Parent", "ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__parent__parent_i__412EB0B6");

                    b.Navigation("ParentNavigation");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.RefreshToken", b =>
                {
                    b.HasOne("NemetschekDnevnik.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Remark", b =>
                {
                    b.HasOne("NemetschekDnevnik.Server.Models.Student", "Student")
                        .WithMany("Remarks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__remarks__student__70DDC3D8");

                    b.HasOne("NemetschekDnevnik.Server.Models.Teacher", "Teacher")
                        .WithMany("Remarks")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("FK__remarks__teacher__71D1E811");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Student", b =>
                {
                    b.HasOne("NemetschekDnevnik.Server.Models.Parent", "Parent")
                        .WithMany("Students")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK__student__parent___44FF419A");

                    b.HasOne("NemetschekDnevnik.Server.Models.User", "StudentNavigation")
                        .WithOne("Student")
                        .HasForeignKey("NemetschekDnevnik.Server.Models.Student", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__student__student__440B1D61");

                    b.Navigation("Parent");

                    b.Navigation("StudentNavigation");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.SubmittedHomework", b =>
                {
                    b.HasOne("NemetschekDnevnik.Server.Models.HomeworkItem", "Homework")
                        .WithMany("SubmittedHomeworks")
                        .HasForeignKey("HomeworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__submitted__homew__7D439ABD");

                    b.HasOne("NemetschekDnevnik.Server.Models.Student", "Student")
                        .WithMany("SubmittedHomeworks")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__submitted__stude__7E37BEF6");

                    b.Navigation("Homework");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Teacher", b =>
                {
                    b.HasOne("NemetschekDnevnik.Server.Models.User", "TeacherNavigation")
                        .WithOne("Teacher")
                        .HasForeignKey("NemetschekDnevnik.Server.Models.Teacher", "TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__teacher__teacher__47DBAE45");

                    b.Navigation("TeacherNavigation");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.WeeklyScheduleItem", b =>
                {
                    b.HasOne("NemetschekDnevnik.Server.Models.Class", "Class")
                        .WithMany("WeeklyScheduleItems")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK__weekly_sc__class__5BE2A6F2");

                    b.HasOne("NemetschekDnevnik.Server.Models.Subject", "Subject")
                        .WithMany("WeeklyScheduleItems")
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("FK__weekly_sc__subje__59FA5E80");

                    b.HasOne("NemetschekDnevnik.Server.Models.Teacher", "Teacher")
                        .WithMany("WeeklyScheduleItems")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("FK__weekly_sc__teach__5AEE82B9");

                    b.Navigation("Class");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("StudentClass", b =>
                {
                    b.HasOne("NemetschekDnevnik.Server.Models.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK__student_c__class__5629CD9C");

                    b.HasOne("NemetschekDnevnik.Server.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__student_c__stude__5535A963");
                });

            modelBuilder.Entity("TeacherSubject", b =>
                {
                    b.HasOne("NemetschekDnevnik.Server.Models.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK__teacher_s__subje__4E88ABD4");

                    b.HasOne("NemetschekDnevnik.Server.Models.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("FK__teacher_s__teach__4D94879B");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Class", b =>
                {
                    b.Navigation("HomeworkItems");

                    b.Navigation("Lessons");

                    b.Navigation("WeeklyScheduleItems");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.GradeType", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.HomeworkItem", b =>
                {
                    b.Navigation("SubmittedHomeworks");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Lesson", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Parent", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Student", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Grades");

                    b.Navigation("Remarks");

                    b.Navigation("SubmittedHomeworks");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Subject", b =>
                {
                    b.Navigation("Grades");

                    b.Navigation("HomeworkItems");

                    b.Navigation("Lessons");

                    b.Navigation("WeeklyScheduleItems");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.Teacher", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Grades");

                    b.Navigation("HomeworkItems");

                    b.Navigation("Lessons");

                    b.Navigation("Remarks");

                    b.Navigation("WeeklyScheduleItems");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.User", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Parent");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("NemetschekDnevnik.Server.Models.WeeklyScheduleItem", b =>
                {
                    b.Navigation("Lessons");
                });
#pragma warning restore 612, 618
        }
    }
}
